version: '3.8'
services:
  postgres:
    image: postgres:13.3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB={{ cookiecutter.package_name }}
    expose:
      - "5432"
    ports:
      - "15432:5432"
    networks:
      - default

  {{ cookiecutter.package_name }}:
    hostname: {{ cookiecutter.package_name }}
    build: .
    ports:
      - "15000:5000"
    expose:
      - "5000"
    volumes:
      - ./:/code/
      - /code/.venv
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/{{ cookiecutter.package_name }}
    command: >
      bash -c "while !</dev/tcp/postgres/5432; do sleep 1; done
      && alembic upgrade head
      && /usr/local/bin/uvicorn {{ cookiecutter.module_name }}.api:fastapi_app --host {{ cookiecutter.package_name }} --reload --port 5000"
    networks:
      - default
    depends_on:
      - postgres

networks:
  default:
